/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.6.dev12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.eve.esi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import enterprises.orbital.eve.esi.client.model.CharacterscharacterIdbookmarksTargetCoordinates;
import enterprises.orbital.eve.esi.client.model.CharacterscharacterIdbookmarksTargetItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * target object
 */
@ApiModel(description = "target object")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-08T14:33:13.072-05:00")
public class CharacterscharacterIdbookmarksTarget   {
  @SerializedName("coordinates")
  private CharacterscharacterIdbookmarksTargetCoordinates coordinates = null;

  @SerializedName("item")
  private CharacterscharacterIdbookmarksTargetItem item = null;

  @SerializedName("location_id")
  private Long locationId = null;

  public CharacterscharacterIdbookmarksTarget coordinates(CharacterscharacterIdbookmarksTargetCoordinates coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @ApiModelProperty(example = "null", value = "")
  public CharacterscharacterIdbookmarksTargetCoordinates getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(CharacterscharacterIdbookmarksTargetCoordinates coordinates) {
    this.coordinates = coordinates;
  }

  public CharacterscharacterIdbookmarksTarget item(CharacterscharacterIdbookmarksTargetItem item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @ApiModelProperty(example = "null", value = "")
  public CharacterscharacterIdbookmarksTargetItem getItem() {
    return item;
  }

  public void setItem(CharacterscharacterIdbookmarksTargetItem item) {
    this.item = item;
  }

  public CharacterscharacterIdbookmarksTarget locationId(Long locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * location_id integer
   * @return locationId
  **/
  @ApiModelProperty(example = "null", required = true, value = "location_id integer")
  public Long getLocationId() {
    return locationId;
  }

  public void setLocationId(Long locationId) {
    this.locationId = locationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CharacterscharacterIdbookmarksTarget characterscharacterIdbookmarksTarget = (CharacterscharacterIdbookmarksTarget) o;
    return Objects.equals(this.coordinates, characterscharacterIdbookmarksTarget.coordinates) &&
        Objects.equals(this.item, characterscharacterIdbookmarksTarget.item) &&
        Objects.equals(this.locationId, characterscharacterIdbookmarksTarget.locationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coordinates, item, locationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CharacterscharacterIdbookmarksTarget {\n");
    
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

