/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.6.dev12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.eve.esi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import enterprises.orbital.eve.esi.client.model.GetCharactersCharacterIdSkillsOkSkills;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-08T14:33:13.072-05:00")
public class GetCharactersCharacterIdSkillsOk   {
  @SerializedName("skills")
  private List<GetCharactersCharacterIdSkillsOkSkills> skills = new ArrayList<GetCharactersCharacterIdSkillsOkSkills>();

  @SerializedName("total_sp")
  private Long totalSp = null;

  public GetCharactersCharacterIdSkillsOk skills(List<GetCharactersCharacterIdSkillsOkSkills> skills) {
    this.skills = skills;
    return this;
  }

  public GetCharactersCharacterIdSkillsOk addSkillsItem(GetCharactersCharacterIdSkillsOkSkills skillsItem) {
    this.skills.add(skillsItem);
    return this;
  }

   /**
   * skills array
   * @return skills
  **/
  @ApiModelProperty(example = "null", value = "skills array")
  public List<GetCharactersCharacterIdSkillsOkSkills> getSkills() {
    return skills;
  }

  public void setSkills(List<GetCharactersCharacterIdSkillsOkSkills> skills) {
    this.skills = skills;
  }

  public GetCharactersCharacterIdSkillsOk totalSp(Long totalSp) {
    this.totalSp = totalSp;
    return this;
  }

   /**
   * total_sp integer
   * @return totalSp
  **/
  @ApiModelProperty(example = "null", value = "total_sp integer")
  public Long getTotalSp() {
    return totalSp;
  }

  public void setTotalSp(Long totalSp) {
    this.totalSp = totalSp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdSkillsOk getCharactersCharacterIdSkillsOk = (GetCharactersCharacterIdSkillsOk) o;
    return Objects.equals(this.skills, getCharactersCharacterIdSkillsOk.skills) &&
        Objects.equals(this.totalSp, getCharactersCharacterIdSkillsOk.totalSp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(skills, totalSp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdSkillsOk {\n");
    
    sb.append("    skills: ").append(toIndentedString(skills)).append("\n");
    sb.append("    totalSp: ").append(toIndentedString(totalSp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

