/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.6.dev12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.eve.esi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import enterprises.orbital.eve.esi.client.model.GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * route object
 */
@ApiModel(description = "route object")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-08T14:33:13.072-05:00")
public class GetCharactersCharacterIdPlanetsPlanetIdOkRoutes   {
  @SerializedName("content_type_id")
  private Integer contentTypeId = null;

  @SerializedName("destination_pin_id")
  private Long destinationPinId = null;

  @SerializedName("quantity")
  private Long quantity = null;

  @SerializedName("route_id")
  private Long routeId = null;

  @SerializedName("source_pin_id")
  private Long sourcePinId = null;

  @SerializedName("waypoints")
  private List<GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints> waypoints = new ArrayList<GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints>();

  public GetCharactersCharacterIdPlanetsPlanetIdOkRoutes contentTypeId(Integer contentTypeId) {
    this.contentTypeId = contentTypeId;
    return this;
  }

   /**
   * content_type_id integer
   * @return contentTypeId
  **/
  @ApiModelProperty(example = "null", required = true, value = "content_type_id integer")
  public Integer getContentTypeId() {
    return contentTypeId;
  }

  public void setContentTypeId(Integer contentTypeId) {
    this.contentTypeId = contentTypeId;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdOkRoutes destinationPinId(Long destinationPinId) {
    this.destinationPinId = destinationPinId;
    return this;
  }

   /**
   * destination_pin_id integer
   * @return destinationPinId
  **/
  @ApiModelProperty(example = "null", required = true, value = "destination_pin_id integer")
  public Long getDestinationPinId() {
    return destinationPinId;
  }

  public void setDestinationPinId(Long destinationPinId) {
    this.destinationPinId = destinationPinId;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdOkRoutes quantity(Long quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * quantity integer
   * @return quantity
  **/
  @ApiModelProperty(example = "null", required = true, value = "quantity integer")
  public Long getQuantity() {
    return quantity;
  }

  public void setQuantity(Long quantity) {
    this.quantity = quantity;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdOkRoutes routeId(Long routeId) {
    this.routeId = routeId;
    return this;
  }

   /**
   * route_id integer
   * @return routeId
  **/
  @ApiModelProperty(example = "null", required = true, value = "route_id integer")
  public Long getRouteId() {
    return routeId;
  }

  public void setRouteId(Long routeId) {
    this.routeId = routeId;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdOkRoutes sourcePinId(Long sourcePinId) {
    this.sourcePinId = sourcePinId;
    return this;
  }

   /**
   * source_pin_id integer
   * @return sourcePinId
  **/
  @ApiModelProperty(example = "null", required = true, value = "source_pin_id integer")
  public Long getSourcePinId() {
    return sourcePinId;
  }

  public void setSourcePinId(Long sourcePinId) {
    this.sourcePinId = sourcePinId;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdOkRoutes waypoints(List<GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints> waypoints) {
    this.waypoints = waypoints;
    return this;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdOkRoutes addWaypointsItem(GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints waypointsItem) {
    this.waypoints.add(waypointsItem);
    return this;
  }

   /**
   * waypoints array
   * @return waypoints
  **/
  @ApiModelProperty(example = "null", value = "waypoints array")
  public List<GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints> getWaypoints() {
    return waypoints;
  }

  public void setWaypoints(List<GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints> waypoints) {
    this.waypoints = waypoints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdPlanetsPlanetIdOkRoutes getCharactersCharacterIdPlanetsPlanetIdOkRoutes = (GetCharactersCharacterIdPlanetsPlanetIdOkRoutes) o;
    return Objects.equals(this.contentTypeId, getCharactersCharacterIdPlanetsPlanetIdOkRoutes.contentTypeId) &&
        Objects.equals(this.destinationPinId, getCharactersCharacterIdPlanetsPlanetIdOkRoutes.destinationPinId) &&
        Objects.equals(this.quantity, getCharactersCharacterIdPlanetsPlanetIdOkRoutes.quantity) &&
        Objects.equals(this.routeId, getCharactersCharacterIdPlanetsPlanetIdOkRoutes.routeId) &&
        Objects.equals(this.sourcePinId, getCharactersCharacterIdPlanetsPlanetIdOkRoutes.sourcePinId) &&
        Objects.equals(this.waypoints, getCharactersCharacterIdPlanetsPlanetIdOkRoutes.waypoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentTypeId, destinationPinId, quantity, routeId, sourcePinId, waypoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdPlanetsPlanetIdOkRoutes {\n");
    
    sb.append("    contentTypeId: ").append(toIndentedString(contentTypeId)).append("\n");
    sb.append("    destinationPinId: ").append(toIndentedString(destinationPinId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    routeId: ").append(toIndentedString(routeId)).append("\n");
    sb.append("    sourcePinId: ").append(toIndentedString(sourcePinId)).append("\n");
    sb.append("    waypoints: ").append(toIndentedString(waypoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

