/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.6.dev12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.eve.esi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import enterprises.orbital.eve.esi.client.model.GetCharactersCharacterIdMailLabelsOkLabels;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-08T14:33:13.072-05:00")
public class GetCharactersCharacterIdMailLabelsOk   {
  @SerializedName("labels")
  private List<GetCharactersCharacterIdMailLabelsOkLabels> labels = new ArrayList<GetCharactersCharacterIdMailLabelsOkLabels>();

  @SerializedName("total_unread_count")
  private Integer totalUnreadCount = null;

  public GetCharactersCharacterIdMailLabelsOk labels(List<GetCharactersCharacterIdMailLabelsOkLabels> labels) {
    this.labels = labels;
    return this;
  }

  public GetCharactersCharacterIdMailLabelsOk addLabelsItem(GetCharactersCharacterIdMailLabelsOkLabels labelsItem) {
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * labels array
   * @return labels
  **/
  @ApiModelProperty(example = "null", value = "labels array")
  public List<GetCharactersCharacterIdMailLabelsOkLabels> getLabels() {
    return labels;
  }

  public void setLabels(List<GetCharactersCharacterIdMailLabelsOkLabels> labels) {
    this.labels = labels;
  }

  public GetCharactersCharacterIdMailLabelsOk totalUnreadCount(Integer totalUnreadCount) {
    this.totalUnreadCount = totalUnreadCount;
    return this;
  }

   /**
   * total_unread_count integer
   * minimum: 0.0
   * @return totalUnreadCount
  **/
  @ApiModelProperty(example = "null", value = "total_unread_count integer")
  public Integer getTotalUnreadCount() {
    return totalUnreadCount;
  }

  public void setTotalUnreadCount(Integer totalUnreadCount) {
    this.totalUnreadCount = totalUnreadCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdMailLabelsOk getCharactersCharacterIdMailLabelsOk = (GetCharactersCharacterIdMailLabelsOk) o;
    return Objects.equals(this.labels, getCharactersCharacterIdMailLabelsOk.labels) &&
        Objects.equals(this.totalUnreadCount, getCharactersCharacterIdMailLabelsOk.totalUnreadCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, totalUnreadCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdMailLabelsOk {\n");
    
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    totalUnreadCount: ").append(toIndentedString(totalUnreadCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

