/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.6.dev12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.eve.esi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * link object
 */
@ApiModel(description = "link object")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-08T14:33:13.072-05:00")
public class GetCharactersCharacterIdPlanetsPlanetIdOkLinks   {
  @SerializedName("destination_pin_id")
  private Long destinationPinId = null;

  @SerializedName("link_level")
  private Integer linkLevel = null;

  @SerializedName("source_pin_id")
  private Long sourcePinId = null;

  public GetCharactersCharacterIdPlanetsPlanetIdOkLinks destinationPinId(Long destinationPinId) {
    this.destinationPinId = destinationPinId;
    return this;
  }

   /**
   * destination_pin_id integer
   * @return destinationPinId
  **/
  @ApiModelProperty(example = "null", required = true, value = "destination_pin_id integer")
  public Long getDestinationPinId() {
    return destinationPinId;
  }

  public void setDestinationPinId(Long destinationPinId) {
    this.destinationPinId = destinationPinId;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdOkLinks linkLevel(Integer linkLevel) {
    this.linkLevel = linkLevel;
    return this;
  }

   /**
   * link_level integer
   * minimum: 0.0
   * maximum: 10.0
   * @return linkLevel
  **/
  @ApiModelProperty(example = "null", required = true, value = "link_level integer")
  public Integer getLinkLevel() {
    return linkLevel;
  }

  public void setLinkLevel(Integer linkLevel) {
    this.linkLevel = linkLevel;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdOkLinks sourcePinId(Long sourcePinId) {
    this.sourcePinId = sourcePinId;
    return this;
  }

   /**
   * source_pin_id integer
   * @return sourcePinId
  **/
  @ApiModelProperty(example = "null", required = true, value = "source_pin_id integer")
  public Long getSourcePinId() {
    return sourcePinId;
  }

  public void setSourcePinId(Long sourcePinId) {
    this.sourcePinId = sourcePinId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdPlanetsPlanetIdOkLinks getCharactersCharacterIdPlanetsPlanetIdOkLinks = (GetCharactersCharacterIdPlanetsPlanetIdOkLinks) o;
    return Objects.equals(this.destinationPinId, getCharactersCharacterIdPlanetsPlanetIdOkLinks.destinationPinId) &&
        Objects.equals(this.linkLevel, getCharactersCharacterIdPlanetsPlanetIdOkLinks.linkLevel) &&
        Objects.equals(this.sourcePinId, getCharactersCharacterIdPlanetsPlanetIdOkLinks.sourcePinId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationPinId, linkLevel, sourcePinId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdPlanetsPlanetIdOkLinks {\n");
    
    sb.append("    destinationPinId: ").append(toIndentedString(destinationPinId)).append("\n");
    sb.append("    linkLevel: ").append(toIndentedString(linkLevel)).append("\n");
    sb.append("    sourcePinId: ").append(toIndentedString(sourcePinId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

