/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.6.dev12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.eve.esi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-08T14:33:13.072-05:00")
public class GetCharactersCharacterIdContactsLabels200Ok   {
  @SerializedName("label_id")
  private Long labelId = null;

  @SerializedName("label_name")
  private String labelName = null;

  public GetCharactersCharacterIdContactsLabels200Ok labelId(Long labelId) {
    this.labelId = labelId;
    return this;
  }

   /**
   * label_id integer
   * @return labelId
  **/
  @ApiModelProperty(example = "null", required = true, value = "label_id integer")
  public Long getLabelId() {
    return labelId;
  }

  public void setLabelId(Long labelId) {
    this.labelId = labelId;
  }

  public GetCharactersCharacterIdContactsLabels200Ok labelName(String labelName) {
    this.labelName = labelName;
    return this;
  }

   /**
   * label_name string
   * @return labelName
  **/
  @ApiModelProperty(example = "null", required = true, value = "label_name string")
  public String getLabelName() {
    return labelName;
  }

  public void setLabelName(String labelName) {
    this.labelName = labelName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdContactsLabels200Ok getCharactersCharacterIdContactsLabels200Ok = (GetCharactersCharacterIdContactsLabels200Ok) o;
    return Objects.equals(this.labelId, getCharactersCharacterIdContactsLabels200Ok.labelId) &&
        Objects.equals(this.labelName, getCharactersCharacterIdContactsLabels200Ok.labelName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labelId, labelName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdContactsLabels200Ok {\n");
    
    sb.append("    labelId: ").append(toIndentedString(labelId)).append("\n");
    sb.append("    labelName: ").append(toIndentedString(labelName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

