/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.6.dev12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package enterprises.orbital.eve.esi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import enterprises.orbital.eve.esi.client.model.GetKillmailsKillmailIdKillmailHashOkVictimItems1;
import enterprises.orbital.eve.esi.client.model.GetKillmailsKillmailIdKillmailHashOkVictimPosition;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * victim object
 */
@ApiModel(description = "victim object")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-08T14:33:13.072-05:00")
public class GetKillmailsKillmailIdKillmailHashOkVictim   {
  @SerializedName("alliance_id")
  private Integer allianceId = null;

  @SerializedName("character_id")
  private Integer characterId = null;

  @SerializedName("corporation_id")
  private Integer corporationId = null;

  @SerializedName("damage_taken")
  private Integer damageTaken = null;

  @SerializedName("faction_id")
  private Integer factionId = null;

  @SerializedName("items")
  private List<GetKillmailsKillmailIdKillmailHashOkVictimItems1> items = new ArrayList<GetKillmailsKillmailIdKillmailHashOkVictimItems1>();

  @SerializedName("position")
  private GetKillmailsKillmailIdKillmailHashOkVictimPosition position = null;

  @SerializedName("ship_type_id")
  private Integer shipTypeId = null;

  public GetKillmailsKillmailIdKillmailHashOkVictim allianceId(Integer allianceId) {
    this.allianceId = allianceId;
    return this;
  }

   /**
   * alliance_id integer
   * @return allianceId
  **/
  @ApiModelProperty(example = "null", value = "alliance_id integer")
  public Integer getAllianceId() {
    return allianceId;
  }

  public void setAllianceId(Integer allianceId) {
    this.allianceId = allianceId;
  }

  public GetKillmailsKillmailIdKillmailHashOkVictim characterId(Integer characterId) {
    this.characterId = characterId;
    return this;
  }

   /**
   * character_id integer
   * @return characterId
  **/
  @ApiModelProperty(example = "null", value = "character_id integer")
  public Integer getCharacterId() {
    return characterId;
  }

  public void setCharacterId(Integer characterId) {
    this.characterId = characterId;
  }

  public GetKillmailsKillmailIdKillmailHashOkVictim corporationId(Integer corporationId) {
    this.corporationId = corporationId;
    return this;
  }

   /**
   * corporation_id integer
   * @return corporationId
  **/
  @ApiModelProperty(example = "null", value = "corporation_id integer")
  public Integer getCorporationId() {
    return corporationId;
  }

  public void setCorporationId(Integer corporationId) {
    this.corporationId = corporationId;
  }

  public GetKillmailsKillmailIdKillmailHashOkVictim damageTaken(Integer damageTaken) {
    this.damageTaken = damageTaken;
    return this;
  }

   /**
   * How much total damage was taken by the victim 
   * @return damageTaken
  **/
  @ApiModelProperty(example = "null", required = true, value = "How much total damage was taken by the victim ")
  public Integer getDamageTaken() {
    return damageTaken;
  }

  public void setDamageTaken(Integer damageTaken) {
    this.damageTaken = damageTaken;
  }

  public GetKillmailsKillmailIdKillmailHashOkVictim factionId(Integer factionId) {
    this.factionId = factionId;
    return this;
  }

   /**
   * faction_id integer
   * @return factionId
  **/
  @ApiModelProperty(example = "null", value = "faction_id integer")
  public Integer getFactionId() {
    return factionId;
  }

  public void setFactionId(Integer factionId) {
    this.factionId = factionId;
  }

  public GetKillmailsKillmailIdKillmailHashOkVictim items(List<GetKillmailsKillmailIdKillmailHashOkVictimItems1> items) {
    this.items = items;
    return this;
  }

  public GetKillmailsKillmailIdKillmailHashOkVictim addItemsItem(GetKillmailsKillmailIdKillmailHashOkVictimItems1 itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * items array
   * @return items
  **/
  @ApiModelProperty(example = "null", value = "items array")
  public List<GetKillmailsKillmailIdKillmailHashOkVictimItems1> getItems() {
    return items;
  }

  public void setItems(List<GetKillmailsKillmailIdKillmailHashOkVictimItems1> items) {
    this.items = items;
  }

  public GetKillmailsKillmailIdKillmailHashOkVictim position(GetKillmailsKillmailIdKillmailHashOkVictimPosition position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(example = "null", value = "")
  public GetKillmailsKillmailIdKillmailHashOkVictimPosition getPosition() {
    return position;
  }

  public void setPosition(GetKillmailsKillmailIdKillmailHashOkVictimPosition position) {
    this.position = position;
  }

  public GetKillmailsKillmailIdKillmailHashOkVictim shipTypeId(Integer shipTypeId) {
    this.shipTypeId = shipTypeId;
    return this;
  }

   /**
   * The ship that the victim was piloting and was destroyed 
   * @return shipTypeId
  **/
  @ApiModelProperty(example = "null", required = true, value = "The ship that the victim was piloting and was destroyed ")
  public Integer getShipTypeId() {
    return shipTypeId;
  }

  public void setShipTypeId(Integer shipTypeId) {
    this.shipTypeId = shipTypeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetKillmailsKillmailIdKillmailHashOkVictim getKillmailsKillmailIdKillmailHashOkVictim = (GetKillmailsKillmailIdKillmailHashOkVictim) o;
    return Objects.equals(this.allianceId, getKillmailsKillmailIdKillmailHashOkVictim.allianceId) &&
        Objects.equals(this.characterId, getKillmailsKillmailIdKillmailHashOkVictim.characterId) &&
        Objects.equals(this.corporationId, getKillmailsKillmailIdKillmailHashOkVictim.corporationId) &&
        Objects.equals(this.damageTaken, getKillmailsKillmailIdKillmailHashOkVictim.damageTaken) &&
        Objects.equals(this.factionId, getKillmailsKillmailIdKillmailHashOkVictim.factionId) &&
        Objects.equals(this.items, getKillmailsKillmailIdKillmailHashOkVictim.items) &&
        Objects.equals(this.position, getKillmailsKillmailIdKillmailHashOkVictim.position) &&
        Objects.equals(this.shipTypeId, getKillmailsKillmailIdKillmailHashOkVictim.shipTypeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allianceId, characterId, corporationId, damageTaken, factionId, items, position, shipTypeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetKillmailsKillmailIdKillmailHashOkVictim {\n");
    
    sb.append("    allianceId: ").append(toIndentedString(allianceId)).append("\n");
    sb.append("    characterId: ").append(toIndentedString(characterId)).append("\n");
    sb.append("    corporationId: ").append(toIndentedString(corporationId)).append("\n");
    sb.append("    damageTaken: ").append(toIndentedString(damageTaken)).append("\n");
    sb.append("    factionId: ").append(toIndentedString(factionId)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    shipTypeId: ").append(toIndentedString(shipTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

